name: WordPress UAT

concurrency:
  group: uat
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      is_ref:
        description: 'Inline Spoilers - GitHub Branch'
        default: 'master'
        type: string

jobs:
  tests:
    name: UAT
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { wp_core: '5.2', php: '7.1'}
          - { wp_core: '5.2', php: '7.2'}
          - { wp_core: '5.2', php: '7.3'}

          - { wp_core: '5.3', php: '7.1'}
          - { wp_core: '5.3', php: '7.2'}
          - { wp_core: '5.3', php: '7.3'}
          - { wp_core: '5.3', php: '7.4'}

          - { wp_core: '5.4', php: '7.2'}
          - { wp_core: '5.4', php: '7.3'}
          - { wp_core: '5.4', php: '7.4'}

          - { wp_core: '5.5', php: '7.2'}
          - { wp_core: '5.5', php: '7.3'}
          - { wp_core: '5.5', php: '7.4'}

          - { wp_core: '5.6', php: '7.2'}
          - { wp_core: '5.6', php: '7.3'}
          - { wp_core: '5.6', php: '7.4'}
          - { wp_core: '5.6', php: '8.0'}

          - { wp_core: '5.7', php: '7.3'}
          - { wp_core: '5.7', php: '7.4'}
          - { wp_core: '5.7', php: '8.0'}

          - { wp_core: '5.8', php: '7.3'}
          - { wp_core: '5.8', php: '7.4'}
          - { wp_core: '5.8', php: '8.0'}

          - { wp_core: '5.9', php: '7.3'}
          - { wp_core: '5.9', php: '7.4'}
          - { wp_core: '5.9', php: '8.0'}
          - { wp_core: '5.9', php: '8.1'}

          - { wp_core: '6.0', php: '7.4'}
          - { wp_core: '6.0', php: '8.0'}
          - { wp_core: '6.0', php: '8.1'}

          - { wp_core: '6.1', php: '7.4'}
          - { wp_core: '6.1', php: '8.0'}
          - { wp_core: '6.1', php: '8.1'}
          - { wp_core: '6.1', php: '8.2'}

          - { wp_core: '6.2', php: '8.0'}
          - { wp_core: '6.2', php: '8.1'}
          - { wp_core: '6.2', php: '8.2'}

          - { wp_core: '6.3', php: '8.0'}
          - { wp_core: '6.3', php: '8.1'}
          - { wp_core: '6.3', php: '8.2'}

          - { wp_core: '6.4', php: '8.0'}
          - { wp_core: '6.4', php: '8.1'}
          - { wp_core: '6.4', php: '8.2'}
          - { wp_core: '6.4', php: '8.3'}

          - { wp_core: '6.5', php: '8.1'}
          - { wp_core: '6.5', php: '8.2'}
          - { wp_core: '6.5', php: '8.3'}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.1'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - uses: actions/checkout@v4
        with:
          repository: sergeykuzmich/inline-spoilers
          ref: ${{ inputs.is_ref }}
          path: './inline-spoilers'
      
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.WP_DEVELOPMENT_ENV_KEY }}
          repository: sergeykuzmich/wp-development-environment
          path: './wp-development-environment'
      - name: Boot WordPress Application
        env:
          WP_CORE: ${{ matrix.wp_core }}
          PHP: ${{ matrix.php }}
        run: |
          cd wp-development-environment
          docker compose up --detach --wait

      - name: Execute Cypress
        env:
          CYPRESS_WP_CORE: ${{ matrix.wp_core }}
        run: yarn cypress run

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.wp_core }}-${{ matrix.php }}-s
          path: cypress/screenshots
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ matrix.wp_core }}-${{ matrix.php }}-v
          path: cypress/videos
